###################################
# Exemplo de arquivo de submissão #
# para execução do aplicativo     #
# que calculapi			  #
###################################
getenv 		= true
universe    	= vanilla
executable  	= $ENV(HOME)/condor-examples/Example2/calculapi
arguments	= 10000000
notification 	= Complete
notify_user 	= carlosadean@linea.gov.br
error 		= example2-$(Process).err
output 		= example2-$(Process).out
log 		= example2-$(Process).log

queue

