######################################
# Arquivo de submissão para o hello  #
# world paralelo com mpi 	     #	
######################################
universe        = parallel
getenv          = true
executable      = $ENV(HOME)/condor-examples/Example3/openmpiscript
arguments       = hello_world_with_mpi
machine_count   = 100

log             = example3-$(Process).log
output          = example3-$(Process).out
error		= example3-$(Process).err

queue
